import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, LogIn, ShieldCheck } from 'lucide-react'
import SiteFooter from '../components/SiteFooter'
import { API_BASE } from '../lib/api'
import { Button, Card, Field, Input } from '../components/UI'

function Login(){const navigate=useNavigate();const[message,setMessage]=useState('');const[saving,setSaving]=useState(false)
async function submit(e){e.preventDefault();setMessage('');setSaving(true);const fd=new FormData(e.target);try{const r=await fetch(`${API_BASE}/api/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});const d=await r.json();if(!r.ok){setMessage(d.detail||'Correo o contraseña incorrectos.');return}localStorage.setItem('user',JSON.stringify({id:d.id,email:d.email}));navigate('/panel')}catch{setMessage('No se pudo conectar con el servidor.')}finally{setSaving(false)}}
return <div className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-6xl px-5 py-6 sm:px-6"><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-ink/60 hover:text-ink"><ArrowLeft size={16}/> Precio Inbox</Link></div><main className="mx-auto grid max-w-5xl gap-10 px-5 pb-16 pt-6 sm:px-6 lg:grid-cols-5 lg:items-center"><section className="lg:col-span-2"><span className="grid size-12 place-items-center rounded-2xl bg-ink text-paper"><LogIn/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-brand">Tu mostrador</p><h1 className="mt-2 font-display text-4xl font-bold leading-tight">Vuelve a tu catálogo.</h1><p className="mt-4 text-sm leading-6 text-ink-soft">Administra productos, fotos, precios y disponibilidad desde un solo lugar.</p><div className="mt-7 flex items-center gap-2 text-sm font-semibold text-ink/60"><ShieldCheck size={17} className="text-brand"/> Acceso seguro con tu cuenta</div></section><Card className="p-6 sm:p-8 lg:col-span-3"><h2 className="font-display text-2xl font-bold">Iniciar sesión</h2><p className="mt-2 text-sm text-ink-soft">Accede a tu catálogo.</p><form className="mt-7 space-y-5" onSubmit={submit}><Field label="Correo electrónico"><Input name="email" type="email" autoComplete="email" required/></Field><Field label="Contraseña"><Input name="password" type="password" autoComplete="current-password" required/></Field>{message&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{message}</div>}<Button type="submit" className="w-full" disabled={saving}>{saving?'Entrando...':'Iniciar sesión'}</Button></form><p className="mt-6 text-center text-sm text-ink/55">¿No tienes cuenta? <Link to="/registro" className="font-semibold text-brand hover:underline">Crea una</Link></p></Card></main><SiteFooter/></div>}
export default Login
