import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, Mail, ShieldCheck } from 'lucide-react'
import SiteFooter from '../components/SiteFooter'
import { API_BASE } from '../lib/api'
import { Button, Card, Field, Input } from '../components/UI'

function Registro(){const[message,setMessage]=useState('');const[success,setSuccess]=useState(false);const[saving,setSaving]=useState(false)
async function submit(e){e.preventDefault();setMessage('');setSaving(true);const fd=new FormData(e.target);try{const r=await fetch(`${API_BASE}/api/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});const d=await r.json();if(!r.ok){setMessage(d.detail||'No fue posible crear la cuenta.');return}setSuccess(true);e.target.reset()}catch{setMessage('No se pudo conectar con el servidor.')}finally{setSaving(false)}}
return <div className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-6xl px-5 py-6 sm:px-6"><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-ink/60 hover:text-ink"><ArrowLeft size={16}/> Precio Inbox</Link></div><main className="mx-auto grid max-w-5xl gap-10 px-5 pb-16 pt-6 sm:px-6 lg:grid-cols-5 lg:items-center"><section className="lg:col-span-2"><span className="grid size-12 place-items-center rounded-2xl bg-brand text-paper"><Mail/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-brand">Empieza aquí</p><h1 className="mt-2 font-display text-4xl font-bold leading-tight">Crea tu catálogo y ponlo a trabajar.</h1><p className="mt-4 text-sm leading-6 text-ink-soft">Regístrate con tu correo. Verifica tu cuenta y después podrás crear tu catálogo.</p><div className="mt-7 space-y-3 text-sm text-ink-soft"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-brand" size={17}/><span>Una URL pública para compartir.</span></div><div className="flex gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-brand" size={17}/><span>Precios y disponibilidad visibles.</span></div><div className="flex gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-brand" size={17}/><span>Pedidos directos por WhatsApp.</span></div></div></section><Card className="p-6 sm:p-8 lg:col-span-3">{success?<div className="py-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-sage/25 text-ink"><ShieldCheck/></span><h2 className="mt-5 font-display text-2xl font-bold">Revisa tu correo</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-ink-soft">Te enviamos un enlace para verificar tu cuenta. Confírmalo y después inicia sesión para crear tu catálogo.</p><Link to="/login" className="mt-7 inline-flex rounded-full bg-ink px-5 py-3 text-sm font-semibold text-paper">Ir a iniciar sesión</Link></div>:<><h2 className="font-display text-2xl font-bold">Crear cuenta</h2><p className="mt-2 text-sm text-ink-soft">Solo necesitas un correo y una contraseña.</p><form className="mt-7 space-y-5" onSubmit={submit}><Field label="Correo electrónico"><Input name="email" type="email" autoComplete="email" required/></Field><Field label="Contraseña" hint="Mínimo 5 caracteres."><Input name="password" type="password" minLength="5" autoComplete="new-password" required/></Field>{message&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{message}</div>}<Button type="submit" className="w-full" disabled={saving}>{saving?'Creando cuenta...':'Crear cuenta'}</Button></form><p className="mt-6 text-center text-sm text-ink/55">¿Ya tienes una cuenta? <Link to="/login" className="font-semibold text-brand hover:underline">Inicia sesión</Link></p></>}</Card></main><SiteFooter/></div>}
export default Registro
